-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 00:39:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marcosvir_lucasJ
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marcosvir_lucasJ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marcosvir_lucasJ` DEFAULT CHARACTER SET utf8 ;
USE `marcosvir_lucasJ` ;

-- -----------------------------------------------------
-- Table `marcosvir_lucasJ`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcosvir_lucasJ`.`restaurante` (
  `idrestaurante` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrestaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marcosvir_lucasJ`.`lanche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcosvir_lucasJ`.`lanche` (
  `idlanche` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `freteGratis` TINYINT NOT NULL,
  `combo` TINYINT NOT NULL,
  `restaurante_idrestaurante` INT NOT NULL,
  PRIMARY KEY (`idlanche`),
  INDEX `fk_lanche_restaurante_idx` (`restaurante_idrestaurante` ASC) VISIBLE,
  CONSTRAINT `fk_lanche_restaurante`
    FOREIGN KEY (`restaurante_idrestaurante`)
    REFERENCES `marcosvir_lucasJ`.`restaurante` (`idrestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
